username = input('введите имя пользователя- ')
title = input('введите заголовок заметки- ')
content = input('введите описание заметки- ')
status = input('введите статус заметки- ')
created_date = input('введите дату создания заметки (в формате "день-месяц-год", например "10-01-2025")- ')
issue_date = input('введите дату истечения заметки (дедлайн) (в формате "день-месяц-год", например "10-02-2025")- ')
print(username)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)
