username = input('введите имя пользователя- ')
title = input('введите заголовок заметки- ')
title2 = input('введите заголовок заметки 2(если нет то поставьте"-")- ')
title3 = input('введите заголовок заметки 3(если нет то поставьте"-")- ')
content = input('введите описание заметки- ')
status = input('введите статус заметки- ')
created_date = input('введите дату создания заметки (в формате "день-месяц-год", например "10-01-2025")- ')
issue_date = input('введите дату истечения заметки (дедлайн) (в формате "день-месяц-год", например "10-02-2025")- ')
print('Имя пользователя:')
print(username)
print('Заголовки заметки:')
glavniytitle=[title, title2, title3]
print(glavniytitle)
print('Описание заметки:')
print(content)
print('Статус заметки:')
print(status)
print('Дата создания заметки')
print(created_date)
print('Дата истечения заметки')
print(issue_date)
